openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: API pour la gestion des tâches

paths:
  /tasks:
    get:
      summary: Récupère la liste de toutes les tâches
      responses:
        '200':
          description: Récupérer toutes les tâches avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    
    post:
      summary: Crée une ou plusieurs nouvelles tâches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TaskInput'
      responses:
        '201':
          description: liste Tâches créées avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    
    delete:
      summary: Supprime une liste de tâches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: integer
                  description: Liste des identifiants des tâches à supprimer
              required:
                - ids
      responses:
        '200':
          description: Tâches supprimées avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '404':
          description: Une ou plusieurs tâches non trouvées
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/{id}:
    get:
      summary: Récupère une tâche par son identifiant
      parameters:
        - name: id
          in: path
          required: true
          description: Identifiant de la tâche
          schema:
            type: integer
      responses:
        '200':
          description: Tâche récupérée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tâche non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    delete:
      summary: Supprime une tâche par son identifiant
      parameters:
        - name: id
          in: path
          required: true
          description: Identifiant de la tâche à supprimer
          schema:
            type: integer
      responses:
        '200':
          description: Tâche supprimée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tâche non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: "Faire les courses"
        completed:
          type: boolean
          example: false
      required:
        - id
        - title
        - completed
    
    TaskInput:
      type: object
      properties:
        title:
          type: string
          example: "Faire les courses"
        completed:
          type: boolean
          example: false
      required:
        - title
    
    Error:
      type: object
      properties:
        message:
          type: string
          example: "Task not found"
      required:
        - message